---
abstract: unknown
author:
  - 'Skye Shaw <sshaw AT lucas.cis.temple.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-NestedAttributesConstructor
no_index:
  directory:
    - t
    - inc
requires:
  Moose: 2
resources:
  bugtracker: http://github.com/sshaw/MooseX-NestedAttributesConstructor/issues
version: 0.01
